### ISSUE TITLE
Train migrations removed in 0.15 update. Breaks old saves.

### ISSUE THREAD

**Issue by credomane** [justarandomgeek/factorio-color-coding#13]
Was looking for some old blueprints. Loaded up an old 0.12.29 save everything worked except all my trains went poof.

Should probably re-add the train migrations.

**Comment by justarandomgeek** [comment]
quick and dirty workaround: you can load the save with 0.14 first, then upgrade it to 0.15 from there. 

I'll look over the migrations and readd them where appropriate.

**Comment by credomane** [comment]
I was only loading the save for blueprints anyways but I figured adding back the migrations might be a good idea since it doesn't hurt anything in the long run.

**Comment by justarandomgeek** [comment]
Yeah, I just sort of assumed all the saves anyone cared about would have had updates introduced in 0.13 by now, but if that's not the case (clearly!), then the migrations weren't really ready to go yet!

**Comment by credomane** [comment]
I'm working on a PR for this, btw. Two more minutes. :)
