### ISSUE TITLE
Bug:  Mining coloured concrete no longer gives concrete

### ISSUE THREAD

**Issue by m-r-h** [justarandomgeek/factorio-color-coding#3]
When mining a tile you get whatever colour instead of uncoloured.

It's much friendlier to inventory to keep just the uncoloured on mining.

Glad you reverted the rotating behaviour for colours!

**Comment by justarandomgeek** [comment]
Not uncrafting is the intended behavior - this is consistent with the behavior of the stock game's hazard concrete. That said, if you really want it uncrafted on mining, you can adjust MINE_RESULT_TABLE in prototypes/config.lua! :)

**Comment by m-r-h** [comment]
Ah, no worries.   I assumed it was something you missed in regression, so report as bug.

With the way I tend to use it I will just adjust after download.  :)

**Comment by justarandomgeek** [comment]
No problem, the inventory clutter of 10-colors-10-items was most of the reason I'd originally tried to combine items, and I'll probably revisit that again at some point, which will makes mine-to-original much less clutter-y. In the mean time, I prefer to blend with the stock content as closely as reasonable, which means dealing with all the different items! (Chuomiko's AutoTrash is useful in this regard.)
