### ISSUE TITLE
Regenerate Fire Hazard sprites for 0.15

### ISSUE THREAD

**Issue by justarandomgeek** [justarandomgeek/factorio-color-coding#6]
The other colors were regenerated by script, but Fire Hazard will require manual editing to update.

**Comment by credomane** [comment]
I made a 2048x2048 png to use as an overlay for easily recreating the fire-hazard concrete's. Then I just used gimp to apply the overlay to each of the base game's concrete. using 75% opacity and changed the mode from normal to color.

I'm about to commit and PR. See what you think.

Surely imagemagick provides a way to allow you to do that automatically. I did it manually for this round. :)

**Comment by justarandomgeek** [comment]
The imagemagick script was a lucky discovery i found when i went looking for what needed doing - it predates my stewardship of this mod! IM itself is somewhat arcane to me, and I didn't see an obvious way to do stripes (and had no unpatterend stripe template) - it probably is there though.

(Also, drat - if i'd procrastinated a few more minutes i'd only have had to do release packaging once!)

**Comment by justarandomgeek** [comment]
These look great, I'll drop them in and post a new release shortly!

**Comment by credomane** [comment]
Yeah...Sorry. I saw that as I was getting ready to commit it. I didn't check the lua for enabling/disabling firehazard concrete though. So that will need looked at.

**Comment by justarandomgeek** [comment]
That's fine, I need to go back and fix some locales for them too anyway!

**Comment by credomane** [comment]
I spent way too long trying to do automate the imagemagick way. Figured I'd at least get the manual version to you then worry about fixing the script later for regenerating automatically later..

**Comment by justarandomgeek** [comment]
yeah, given the template i can probably trick IM into doing it for next time (if they redo concrete sprites again...)

**Comment by credomane** [comment]
Yeah that is exactly why I included the 2048x2048 px template.
Flipping the template along the horizontal axis makes it fire-hazard-right too! The though occurred to me after I was already part way through making a second template. lol
